import { ECustomer } from "@/lib/entities/customer.entity";
import { ColumnDef } from "@tanstack/react-table";
import { MoreHorizontal } from "lucide-react";

import { Button } from "@/components/ui/button";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuLabel,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";

import { Checkbox } from "@/components/ui/checkbox";
import { DataTableColumnHeader } from "@/components/data-table-column-header";

export const customers: ECustomer[] = [
  {
    id: "c1",
    first_name: "John",
    last_name: "Doe",
    middle_name: "Michael",
    account_ref: "ACC1001",
    full_name: "John Michael Doe",
    gabs_tag: "johnny_d",
    email: "john.doe@example.com",
    has_onboarded: true,
    password: "hashed_password_1",
    phone_number: "+2348012345678",
    bvn_phone_number: "+2348012345678",
    country: "Nigeria",
    status: "active",
    referral_code: "REF123",
    referral_link: "https://gabs.com/ref/REF123",
    referred_by: null,
    referrals: ["c5", "c7"],
    gender: "male",
    providers: {},
    bvn: "22345678901",
    kyc_level: 2,
    nin: "12345678901",
    avatar: "https://example.com/avatar1.png",
    medium: "google",
    date_of_birth: "1990-05-14",
    state_of_origin: "Lagos",
    is_flagged: false,
    platform: "mobile",
    terms: true,
    address: { street: "12 Broad St", city: "Lagos" },
    passcode: "1234",
    secure_pin: "5678",
    refresh_token: [],
    created_at: new Date("2024-01-12"),
  },
  {
    id: "c2",
    first_name: "Mary",
    last_name: "Okafor",
    middle_name: "Chinwe",
    account_ref: "ACC1002",
    full_name: "Mary Chinwe Okafor",
    gabs_tag: "mary_o",
    email: "mary.okafor@example.com",
    has_onboarded: true,
    password: "hashed_password_2",
    phone_number: "+2348098765432",
    bvn_phone_number: "+2348098765432",
    country: "Nigeria",
    status: "active",
    referral_code: "REF234",
    referral_link: "https://gabs.com/ref/REF234",
    referred_by: "c1",
    referrals: [],
    gender: "female",
    providers: {},
    bvn: "32345678901",
    kyc_level: 1,
    nin: "22345678901",
    avatar: "https://example.com/avatar2.png",
    medium: "referral",
    date_of_birth: "1995-09-22",
    state_of_origin: "Anambra",
    is_flagged: false,
    platform: "web",
    terms: true,
    address: { street: "45 Ogui Rd", city: "Enugu" },
    passcode: "2345",
    secure_pin: "6789",
    refresh_token: [],
    created_at: new Date("2024-02-15"),
  },
  {
    id: "c3",
    first_name: "Ahmed",
    last_name: "Bello",
    middle_name: null,
    account_ref: "ACC1003",
    full_name: "Ahmed Bello",
    gabs_tag: "ahmed_b",
    email: "ahmed.bello@example.com",
    has_onboarded: false,
    password: null,
    phone_number: "+2347012345678",
    bvn_phone_number: null,
    country: "Nigeria",
    status: "inactive",
    referral_code: null,
    referral_link: null,
    referred_by: null,
    referrals: [],
    gender: "male",
    providers: {},
    bvn: null,
    kyc_level: 0,
    nin: null,
    avatar: null,
    medium: "facebook",
    date_of_birth: null,
    state_of_origin: "Kano",
    is_flagged: null,
    platform: "mobile",
    terms: false,
    address: null,
    passcode: null,
    secure_pin: null,
    refresh_token: [],
    created_at: new Date("2024-03-01"),
  },
  {
    id: "c4",
    first_name: "Adaeze",
    last_name: "Nwosu",
    middle_name: "Blessing",
    account_ref: "ACC1004",
    full_name: "Adaeze Blessing Nwosu",
    gabs_tag: "ada_bless",
    email: "ada.nwosu@example.com",
    has_onboarded: true,
    password: "hashed_password_4",
    phone_number: "+2348023456789",
    bvn_phone_number: "+2348023456789",
    country: "Nigeria",
    status: "active",
    referral_code: "REF456",
    referral_link: "https://gabs.com/ref/REF456",
    referred_by: "c2",
    referrals: ["c8"],
    gender: "female",
    providers: {},
    bvn: "42345678901",
    kyc_level: 2,
    nin: "32345678901",
    avatar: "https://example.com/avatar4.png",
    medium: "instagram",
    date_of_birth: "1998-12-01",
    state_of_origin: "Imo",
    is_flagged: false,
    platform: "web",
    terms: true,
    address: { street: "78 Douglas Rd", city: "Owerri" },
    passcode: "3456",
    secure_pin: "7890",
    refresh_token: [],
    created_at: new Date("2024-03-18"),
  },
  {
    id: "c5",
    first_name: "Emeka",
    last_name: "Okoro",
    middle_name: null,
    account_ref: "ACC1005",
    full_name: "Emeka Okoro",
    gabs_tag: "emeka_ok",
    email: "emeka.okoro@example.com",
    has_onboarded: true,
    password: "hashed_password_5",
    phone_number: "+2348034567890",
    bvn_phone_number: "+2348034567890",
    country: "Nigeria",
    status: "blocked",
    referral_code: null,
    referral_link: null,
    referred_by: "c1",
    referrals: [],
    gender: "male",
    providers: {},
    bvn: "52345678901",
    kyc_level: 1,
    nin: "42345678901",
    avatar: null,
    medium: "twitter",
    date_of_birth: "1988-03-11",
    state_of_origin: "Abia",
    is_flagged: true,
    platform: "mobile",
    terms: true,
    address: { street: "23 Aba Rd", city: "Aba" },
    passcode: "4567",
    secure_pin: "8901",
    refresh_token: [],
    created_at: new Date("2024-04-05"),
  },
  {
    id: "c6",
    first_name: "Bola",
    last_name: "Adeyemi",
    middle_name: null,
    account_ref: "ACC1006",
    full_name: "Bola Adeyemi",
    gabs_tag: "bola_ad",
    email: "bola.adeyemi@example.com",
    has_onboarded: true,
    password: "hashed_password_6",
    phone_number: "+2348045678901",
    bvn_phone_number: "+2348045678901",
    country: "Nigeria",
    status: "active",
    referral_code: null,
    referral_link: null,
    referred_by: null,
    referrals: [],
    gender: "female",
    providers: {},
    bvn: "62345678901",
    kyc_level: 2,
    nin: "52345678901",
    avatar: null,
    medium: "linkedin",
    date_of_birth: "1992-07-19",
    state_of_origin: "Oyo",
    is_flagged: false,
    platform: "mobile",
    terms: true,
    address: { street: "10 Bodija St", city: "Ibadan" },
    passcode: "5678",
    secure_pin: "9012",
    refresh_token: [],
    created_at: new Date("2024-05-02"),
  },
  {
    id: "c7",
    first_name: "Chidi",
    last_name: "Eze",
    middle_name: "Anthony",
    account_ref: "ACC1007",
    full_name: "Chidi Anthony Eze",
    gabs_tag: "chidi_e",
    email: "chidi.eze@example.com",
    has_onboarded: false,
    password: null,
    phone_number: "+2348056789012",
    bvn_phone_number: null,
    country: "Nigeria",
    status: "inactive",
    referral_code: null,
    referral_link: null,
    referred_by: "c1",
    referrals: [],
    gender: "male",
    providers: {},
    bvn: null,
    kyc_level: 0,
    nin: null,
    avatar: null,
    medium: "friend",
    date_of_birth: null,
    state_of_origin: "Enugu",
    is_flagged: null,
    platform: null,
    terms: false,
    address: null,
    passcode: null,
    secure_pin: null,
    refresh_token: [],
    created_at: new Date("2024-05-15"),
  },
  {
    id: "c8",
    first_name: "Ifunanya",
    last_name: "Obi",
    middle_name: null,
    account_ref: "ACC1008",
    full_name: "Ifunanya Obi",
    gabs_tag: "ifu_obi",
    email: "ifunanya.obi@example.com",
    has_onboarded: true,
    password: "hashed_password_8",
    phone_number: "+2348067890123",
    bvn_phone_number: "+2348067890123",
    country: "Nigeria",
    status: "active",
    referral_code: null,
    referral_link: null,
    referred_by: "c4",
    referrals: [],
    gender: "female",
    providers: {},
    bvn: "72345678901",
    kyc_level: 1,
    nin: "62345678901",
    avatar: null,
    medium: "others",
    date_of_birth: "1994-06-09",
    state_of_origin: "Delta",
    is_flagged: false,
    platform: "web",
    terms: true,
    address: { street: "15 Warri Rd", city: "Warri" },
    passcode: "6789",
    secure_pin: "0123",
    refresh_token: [],
    created_at: new Date("2024-06-10"),
  },
  {
    id: "c9",
    first_name: "Uche",
    last_name: "Ibrahim",
    middle_name: null,
    account_ref: "ACC1009",
    full_name: "Uche Ibrahim",
    gabs_tag: "uche_ib",
    email: "uche.ibrahim@example.com",
    has_onboarded: true,
    password: "hashed_password_9",
    phone_number: "+2348078901234",
    bvn_phone_number: "+2348078901234",
    country: "Nigeria",
    status: "blocked",
    referral_code: null,
    referral_link: null,
    referred_by: null,
    referrals: [],
    gender: "male",
    providers: {},
    bvn: "82345678901",
    kyc_level: 2,
    nin: "72345678901",
    avatar: "https://example.com/avatar9.png",
    medium: "google",
    date_of_birth: "1987-11-30",
    state_of_origin: "Kaduna",
    is_flagged: true,
    platform: "mobile",
    terms: true,
    address: { street: "4 Ahmadu Bello Way", city: "Kaduna" },
    passcode: "7890",
    secure_pin: "1234",
    refresh_token: [],
    created_at: new Date("2024-07-20"),
  },
  {
    id: "c10",
    first_name: "Zainab",
    last_name: "Lawal",
    middle_name: "Aisha",
    account_ref: "ACC1010",
    full_name: "Zainab Aisha Lawal",
    gabs_tag: "zainab_l",
    email: "zainab.lawal@example.com",
    has_onboarded: true,
    password: "hashed_password_10",
    phone_number: "+2348089012345",
    bvn_phone_number: "+2348089012345",
    country: "Nigeria",
    status: "active",
    referral_code: "REF890",
    referral_link: "https://gabs.com/ref/REF890",
    referred_by: null,
    referrals: [],
    gender: "female",
    providers: {},
    bvn: "92345678901",
    kyc_level: 3,
    nin: "82345678901",
    avatar: null,
    medium: "linkedin",
    date_of_birth: "1993-08-25",
    state_of_origin: "Kwara",
    is_flagged: false,
    platform: "web",
    terms: true,
    address: { street: "7 Unity Rd", city: "Ilorin" },
    passcode: "8901",
    secure_pin: "2345",
    refresh_token: [],
    created_at: new Date("2024-08-15"),
  },
];

export const CustomerColumns: ColumnDef<ECustomer>[] = [
  {
    id: "select",
    header: ({ table }) => (
      <Checkbox
        checked={
          table.getIsAllPageRowsSelected() ||
          (table.getIsSomePageRowsSelected() && "indeterminate")
        }
        onCheckedChange={(value) => table.toggleAllPageRowsSelected(!!value)}
        aria-label="Select all"
      />
    ),
    cell: ({ row }) => (
      <Checkbox
        checked={row.getIsSelected()}
        onCheckedChange={(value) => row.toggleSelected(!!value)}
        aria-label="Select row"
      />
    ),
    enableSorting: false,
    enableHiding: false,
  },
  {
    accessorKey: "first_name",
    header: ({ column }) => (
      <DataTableColumnHeader column={column} title="First Name" />
    ),
  },
  {
    accessorKey: "last_name",
    header: ({ column }) => (
      <DataTableColumnHeader column={column} title="Last Name" />
    ),
  },
  {
    accessorKey: "status",
    header: "Status",
  },
  {
    accessorKey: "phone_number",
    header: "Phone Number",
  },
  {
    accessorKey: "email",
    header: "Email",
  },
  {
    id: "actions",
    cell: ({ row }) => {
      const customer = row.original;

      return (
        <DropdownMenu>
          <DropdownMenuTrigger>
            <Button variant="ghost" className="h-8 w-8 p-0">
              <span className="sr-only">Open menu</span>
              <MoreHorizontal className="h-4 w-4" />
            </Button>
          </DropdownMenuTrigger>
          <DropdownMenuContent align="end">
            <DropdownMenuLabel>Actions</DropdownMenuLabel>
            <DropdownMenuItem
              onClick={() => navigator.clipboard.writeText(customer.id)}
            >
              Copy customer ID
            </DropdownMenuItem>
            <DropdownMenuSeparator />
            <DropdownMenuItem>View customer</DropdownMenuItem>
            <DropdownMenuItem>View customer wallet</DropdownMenuItem>
            <DropdownMenuItem>View customer investments</DropdownMenuItem>
          </DropdownMenuContent>
        </DropdownMenu>
      );
    },
  },
];
