

export type ReservedAccountOptions = {
    accountReference: string; // A unique reference generated by merchants
    accountName: string; // The name to be displayed during name enquiry
    currencyCode: "NGN"; // The currency allowed (e.g., NGN)
    contractCode: string; // The merchant contract code
    customerEmail: string; // The customer's email address
    customerName: string; // The customer's full name
    bvn: string; // The BVN attached to the reserved account
    getAllAvailableBanks: boolean; // Indicates whether to retrieve all available banks
};
